version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

    data_tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('other_table_name')
          group_by_columns: # Optional, Columns to group by before executing the test
            - group_id
          description: blaaaa
          config:
            tags:
              - PII
            severity: warn
            warn_if: '!=0'
            limit: 10
          meta:
            owner:
              - joost@elementary-data.com
  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
