version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

    tests:
      - elementary.schema_changes:
          config:
            severity: error
          meta:
            description: Checks for schema changes against an existing baseline
  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
    tests:
      - elementary.schema_changes:
          config:
            severity: error
          meta:
            description: Checks for schema changes against an existing baseline
