version: 2

models:
  - name: stg_customers
    config:
      tags: ["staging", "PII"]
    columns:
      - name: customer_id

  - name: stg_orders
    config:
      tags: ["staging", "finance"]
    columns:
      - name: order_id
      - name: status

      - name: customer_id
        data_tests:
          - dbt_expectations.expect_column_values_to_be_increasing:
              sort_column: date_day
              row_condition: id is not null # Optional
              strictly: true # Optional, Default is 'true', and it uses '>'. If set to 'false' it uses '>='.
              group_by: # Optional
                - group_id
  - name: stg_payments
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
      - name: payment_method

      - name: order_id
        data_tests:
          - not_null:
              description: The order_id column in the stg_payments table should not
                contain null values
  - name: stg_signups
    config:
      tags: ["staging", "PII"]
    columns:
      - name: signup_id
      - name: customer_email
