version: 2

models:
  - name: stg_customers
    config:
      tags: ["staging", "PII"]
    columns:
      - name: customer_id

  - name: stg_orders
    config:
      tags: ["staging", "finance"]
    columns:
      - name: order_id
      - name: status

    tests:
      - elementary.schema_changes:
          config:
            severity: error
          meta:
            description: Checks for schema changes against an existing baseline
  - name: stg_payments
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
      - name: payment_method

  - name: stg_signups
    config:
      tags: ["staging", "PII"]
    columns:
      - name: signup_id
      - name: customer_email
    tests:
      - elementary.schema_changes:
          config:
            severity: error
          meta:
            description: Checks for schema changes against an existing baseline
