version: 2

models:
  - name: stg_customers
    config:
      tags: ["staging", "PII"]
    columns:
      - name: customer_id

  - name: stg_orders
    config:
      tags: ["staging", "finance"]
    columns:
      - name: order_id
      - name: status

  - name: stg_payments
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
      - name: payment_method

      - name: order_id
        data_tests:
          - dbt_utils.at_least_one:
              group_by_columns: # Optional, Columns to group by before executing the test
                - group_id
              config:
                severity: error
              meta:
                owner:
                  - ella+123@elementary-data.com
  - name: stg_signups
    config:
      tags: ["staging", "PII"]
    columns:
      - name: signup_id
      - name: customer_email
