version: 2

models:
  - name: mar_customers
#    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
#    config:
#      tags: ["PII"]

#    columns:
#      - name: customer_id
#        description: This is a unique identifier for a customer
#
#      - name: first_name
#        description: Customer's first name. PII.
#
#      - name: last_name
#        description: Customer's last name. PII.
#
#      - name: first_order
#        description: Date (UTC) of a customer's first order
#
#      - name: most_recent_order
#        description: Date (UTC) of a customer's most recent order
#
#      - name: number_of_orders
#        description: Count of the number of orders a customer has placed
#
#      - name: customer_lifetime_value
#        description: Total value (AUD) of a customer's orders
#
#      - name: customer_email
#        description: Customer's email. PII.
#
#      - name: signup_date
#        description: Date (UTC) of a customer's signup to the online shop.
