version: 2

models:
  - name: fin_date
  - name: two_dates
    data_tests:
      - elementary.volume_anomalies:
          time_bucket:
            period: day
            count: 1
          days_back: 14
          backfill_days: 2
          sensitivity: 3.0
          timestamp_column: c
          description: Checking for anomalies in the size and growth of a table by
            comparing the row count of each 1 days period to the last 14 days
          config:
            severity: error
