models:
  - columns:
      - {description: This is a unique identifier for a customer, name: customer_id}
      - {description: Customer's first name. PII., name: first_name}
      - {description: Customer's last name. PII., name: last_name}
      - {description: Date (UTC) of a customer's first order, name: first_order}
      - {description: Date (UTC) of a customer's most recent order, name: most_recent_order}
      - description: Count of the number of orders a customer has placed
        name: number_of_orders
        tests:
          - not_null:
              config: {severity: error}
              meta: {description: The NUMBER_OF_ORDERS column in the customers table should not contain null values}
      - {description: Total value (AUD) of a customer's orders, name: customer_lifetime_value}
      - {description: Customer's email. PII., name: customer_email}
      - {description: Date (UTC) of a customer's signup to the online shop., name: signup_date}
    config:
      tags: [PII]
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
    name: customers
  - columns:
      - {description: This is a unique identifier for an order, name: order_id}
      - {description: Foreign key to the customers table, name: customer_id}
      - {description: Date (UTC) that the order was placed, name: order_date}
      - {description: '{{ doc("orders_status") }}', name: status}
      - description: Total amount (AUD) of the order
        name: amount
        tests:
          - elementary.column_anomalies:
              column_anomalies: [sum]
              tags: [numeric_column_anomalies]
      - {description: Amount of the order (AUD) paid for by credit card, name: credit_card_amount}
      - {description: Amount of the order (AUD) paid for by coupon, name: coupon_amount}
      - {description: Amount of the order (AUD) paid for by bank transfer, name: bank_transfer_amount}
      - {description: Amount of the order (AUD) paid for by gift card, name: gift_card_amount}
    config:
      tags: [finance]
    description: This table has basic information about orders, as well as some derived facts based on payments
    name: orders
    tests:
      - elementary.schema_changes:
          config: {severity: error}
          meta: {description: Checks for schema changes against an existing baseline}
  - columns:
      - {description: This is a unique identifier for an order, name: order_id}
      - {description: Foreign key to the customers table, name: customer_id}
      - {description: Date (UTC) that the order was placed, name: order_date}
      - {description: '{{ doc("orders_status") }}', name: status}
      - {description: Total amount (AUD) of the order, name: amount}
      - {description: Amount of the order (AUD) paid for by credit card, name: credit_card_amount}
      - {description: Amount of the order (AUD) paid for by coupon, name: coupon_amount}
      - {description: Amount of the order (AUD) paid for by bank transfer, name: bank_transfer_amount}
      - {description: Amount of the order (AUD) paid for by gift card, name: gift_card_amount}
    config:
      tags: [finance]
    description: This table contains all of the returned orders
    name: returned_orders
sources:
  - name: date
    tables:
      - {name: date}
      - columns:
          - name: full_name
            tests: [not_null]
        freshness:
          warn_after: {count: 30, period: day}
        loaded_at_field: created_at
        name: user_data
  - name: date_dev
    tables:
      - {name: date}
version: 2
