version: 2

sources:
  - name: date
    # database: elementary_db
    # schema: fin_schema
    tables:
      - name: date
      - name: user_data
        loaded_at_field: created_at
        freshness:
          warn_after:
            count: 30
            period: day
        columns:
          - name: full_name
            tests:
              - not_null
  - name: date_dev
    # database: dev
    # schema: noya_tests_elementary
    tables:
      - name: date


#sources:
#  - name: date
#    database: elementary_db
#    schema: fin_schema
#    tables:
#      - name: USER_DATA
#  - name: date_dev
#    database: ELEMENTARY_TESTS
#    schema: noya_tests_elementary
#    tables:
#      - name: USER_DATA

models:
  - name: customers
    description: This table has basic information about a customer, as well as some
      derived facts based on a customer's orders
    config:
      tags: ["PII"]

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer

        tests:
          - not_null:
              config:
                severity: error
              meta:
                description: The CUSTOMER_ID column in the customers table should not contain null values
      - name: first_name
        description: Customer's first name. PII.

      - name: last_name
        description: Customer's last name. PII.

      - name: first_order
        description: Date (UTC) of a customer's first order

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order

      - name: number_of_orders
        description: Count of the number of orders a customer has placed

      - name: customer_lifetime_value
        description: Total value (AUD) of a customer's orders

      - name: customer_email
        description: Customer's email. PII.

      - name: signup_date
        description: Date (UTC) of a customer's signup to the online shop.

  - name: orders
    description: This table has basic information about orders, as well as some derived
      facts based on payments
    config:
      tags: ["finance"]

    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'

      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - elementary.column_anomalies:
              column_anomalies:
                - sum
                - max
              tags: ["numeric_column_anomalies"]

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card

    tests:
      - elementary.schema_changes:
          config:
            severity: error
          meta:
            description: Checks for schema changes against an existing baseline
  - name: returned_orders
    description: This table contains all of the returned orders
    config:
      tags: ["finance"]

    columns:
      - name: order_id
        description: This is a unique identifier for an order

        data_tests:
          - not_null
      - name: customer_id
        description: Foreign key to the customers table

        data_tests:
          - not_null
      - name: order_date
        description: Date (UTC) that the order was placed

        data_tests:
          - not_null
      - name: status
        description: '{{ doc("orders_status") }}'

      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - elementary.column_anomalies:
              column_anomalies:
                - sum
              tags: ["numeric_column_anomalies"]
          - elementary.column_anomalies:
              column_anomalies:
                - max
              tags: ["numeric_column_anomalies"]
          - elementary.column_anomalies:
              column_anomalies:
                - min
              tags: ["numeric_column_anomalies"]

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card
